"""
* Django settings for src project.

* Generated by "django-admin startproject" using Django 3.1.

* For more information on this file, see
? https://docs.djangoproject.com/en/3.1/topics/settings/

* For the full list of settings and their values, see
? https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from src.settings.common import *

import environ

env = environ.Env()
environ.Env.read_env()

SECRET_KEY = env("SECRET_KEY")

DEBUG = False

ALLOWED_HOSTS = ["*"]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

DATABASES = {"default": env.db("DATABASE_URL")}

TENANT_USERS_DOMAIN = env("DOMAIN")
